name: Hello World!

on:
    push:
        branches:
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Say hello
              run: |
                  echo "Hello World!"
    date_job:
        runs-on: ubuntu-20.04
        steps:
            - name: check date
              run: date
    ls_job:
        runs-on: ubuntu-20.04
        steps:
            - name: check ls
              run: ls -l
